@startuml

    class CyclicDependencyProblem {
        -row: int
        -cycle: List<VariableIdentifier>
        +CyclicDependencyProblem(row:int, cycle:List<VariableIdentifier>)
        +match(matchTypeError:Function<TypeErrorProblem, R>, matchInvalidIOVar:Function<InvalidIOVarProblem, R>, matchCyclicDependency:Function<CyclicDependencyProblem, R>, matchParseError:Function<ParseErrorProblem, R>, matchDurationProblem:Function<DurationProblem, R>): R
        +getRow(): int
        +getCycle(): List<VariableIdentifier>
    }

@enduml
