@startuml

    class InvalidIOVarProblem {
        -column: VariableIdentifier
        -type: InvalidIOVarProblem.Type
        +InvalidIOVarProblem(column:VariableIdentifier, type:InvalidIOVarProblem.Type)
        +match(matchTypeError:Function<TypeErrorProblem, R>, matchInvalidIOVar:Function<InvalidIOVarProblem, R>, matchCyclicDependency:Function<CyclicDependencyProblem, R>, matchParseError:Function<ParseErrorProblem, R>, matchDurationProblem:Function<DurationProblem, R>): R
        +getVariableIdentifier(): VariableIdentifier
        +getType(): InvalidIOVarProblem.Type
    }

@enduml
