# .github/release.yml

# Documentation:
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - "Ignore in Changelog"
    authors:
      - octocat
      - dependabot
  categories:
    - title: Breaking Changes 🗲
      labels:
        - "Breaking Change"
        - "Breaks API"
        - "breaking"
    - title: Features
      labels:
        - "feature"
    - title: Enhancement
      labels:
        - "enhancement"
    - title: Bug Fixes
      labels:
        - "bug"
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
