@startuml

    class TimingDiagramController {
        +view: TimingDiagramView
        +TimingDiagramController(ioVariable:IOVariable, ioVarValues:SpecificationColumn<ConcreteCell>, selection:Selection)
        +getView(): TimingDiagramView
    }

@enduml
