@startuml

    class RootModel {
        -NUMBER_OF_MEMENTOS: int
        -hybridSpecifications: HashSet<HybridSpecification>
        -globalConfig: GlobalConfig
        -history: History
        -mementos: <any>
        +getHybridSpecifications(): HashSet<HybridSpecification>
        +getGlobalConfig(): GlobalConfig
        +getHistory(): History
        +undo(): void
        +redo(): void
    }

@enduml
