@startuml

    class CounterexampleCellController {
        -text: String
        -counterexampleCell: CounterexampleCell
        +CounterexampleCellController(string:String)
        +getView(): CounterexampleCell
    }

@enduml
