@startuml

    class HybridCellController {
        -comment: StringProperty
        -counterexamples: ObservableList<String>
        -problems: ObservableList<SpecProblem>
        -hybridCell: HybridCell
        +HybridCellController(cell:CellOperationProvider, counterexamples:ObservableList<String>)
        +getCounterexamples(): ObservableList<String>
        +getValueProperty(): StringProperty
        +getCommentProperty(): StringProperty
        +onProblemsChange(problems:List<SpecProblem>): void
        +getView(): HybridCell
    }

@enduml
