@startuml

    namespace edu.kit.iti.formal.stvs.view.spec.table.cells {

        class ValueCell {
            -editableProperty: BooleanProperty
            -valueProperty: StringProperty
            +getEditableProperty(): BooleanProperty
            +setEditable(b:boolean): void
            +getValueProperty(): StringProperty
        }

        class HybridCellController {
            -comment: StringProperty
            -counterexamples: ObservableList<String>
            -problems: ObservableList<SpecProblem>
            +HybridCellController(cell:CellOperationProvider, counterexamples:ObservableList<String>)
            +getCounterexamples(): ObservableList<String>
            +getValueProperty(): StringProperty
            +getCommentProperty(): StringProperty
            +onProblemsChange(problems:List<SpecProblem>): void
        }

        abstract class TableCell {
            -editableProperty: ReadOnlyBooleanProperty
            +getEditableProperty(): ReadOnlyBooleanProperty
            +getEditable(): boolean
        }

        class ValueCellController {
            -value: StringProperty
            +ValueCellController(constraintCell:ConstraintCell)
        }

        class CounterexampleCellController {
            -text: String
            +CounterexampleCellController(string:String)
        }

        class HybridCell {
            -counterExampleContainer: VBox
            -editableProperty: BooleanProperty
            -commentButton: Button
            +getEditableProperty(): BooleanProperty
            +setEditable(b:boolean): void
            +getEditable(): boolean
            +getCounterExampleContainer(): VBox
        }

        class CounterexampleCell {
            -text: String
            +CounterexampleCell(text:String)
        }

        TableCell <|-- ValueCell

        interface edu.kit.iti.formal.stvs.view.Controller {
            {abstract} +getView(): Node
        }
        edu.kit.iti.formal.stvs.view.Controller <|.. HybridCellController

        class javafx.scene.layout.Pane
        javafx.scene.layout.Pane <|-- TableCell

        edu.kit.iti.formal.stvs.view.Controller <|.. ValueCellController

        edu.kit.iti.formal.stvs.view.Controller <|.. CounterexampleCellController

        TableCell <|-- HybridCell

        TableCell <|-- CounterexampleCell

        HybridCellController --> HybridCell: hybridCell\nview

        ValueCellController --> ValueCell: valueCell\nview

        CounterexampleCellController --> CounterexampleCell: counterexampleCell\nview

        HybridCell --> ValueCell: valueCell

    }

@enduml
