@startuml

    class ValueCellController {
        -valueCell: ValueCell
        -value: StringProperty
        +ValueCellController(constraintCell:ConstraintCell)
        +getView(): ValueCell
    }

@enduml
