@startuml

    class GlobalConfig {
        -verificationTimeout: int
        -simulationTimeout: int
        -windowHeight: int
        -windowWidth: int
        -editorFontSize: int
        -editorFontFamily: String
        -showLineNumbers: boolean
        -uiLanguage: String
        +GlobalConfig()
        +GlobalConfig(conf:GlobalConfig)
        +getVerificationTimeout(): int
        +getSimulationTimeout(): int
        +getEditorFontSize(): int
        +getEditorFontFamily(): String
        +getShowLineNumbers(): boolean
        +getUiLanguage(): String
        +setVerificationTimeout(verificationTimeout:int): void
        +setSimulationTimeout(simulationTimeout:int): void
        +setEditorFontSize(editorFontSize:int): void
        +setEditorFontFamily(editorFontFamily:String): void
        +setShowLineNumbers(showLineNumbers:boolean): void
        +setUiLanguage(uiLanguage:String): void
        +getWindowHeight(): int
        +setWindowHeight(windowHeight:int): void
        +getWindowWidth(): int
        +setWindowWidth(windowWidth:int): void
    }

@enduml
