@startuml

    class History {
        -codeFiles: ArrayList<String>
        -specFiles: ArrayList<String>
        +getCodeFiles(): Collection<String>
        +getSpecFiles(): Collection<String>
        +addCodeFile(filename:String): void
        +addSpecFile(filename:String): void
    }

@enduml
