@startuml

    abstract class CategoryTableController {
        -title: String
        -spec: HybridSpecification
        -types: ObservableList<Type>
        -ioVars: ObservableList<IOVariable>
        -categoryTable: CategoryTable
        -columns: ObservableMap<VariableIdentifier, ColumnController>
        -columnIndices: Map<ColumnController, Integer>
        -sortedColumns: ObservableList<ColumnController>
        +CategoryTableController(title:String, spec:HybridSpecification, types:ObservableList<Type>, ioVars:ObservableList<IOVariable>, tablePaneController:TablePaneController)
        #onColumnChange(change:SpecificationTable.ColumnChangeInfo<ConstraintCell>): void
        +getColumns(): ObservableList<ColumnController>
        +getView(): CategoryTable
        {abstract} +addIOVariable(string:String): void
    }

@enduml
