@startuml

    abstract class ColumnController {
        +ColumnController(config:ColumnConfig)
        {abstract} +onProblemsChange(problems:List<SpecProblem>): void
        {abstract} +getWidthProperty(): IntegerProperty
        {abstract} +getWidth(): int
        {abstract} +getCells(): ObservableList<HybridCellController>
        {abstract} +getView(): Node
    }

@enduml
