@startuml

    class InputTableController {
        +InputTableController(spec:HybridSpecification, types:ObservableList<Type>, ioVars:ObservableList<IOVariable>, tablePaneController:TablePaneController)
        +addIOVariable(string:String): void
    }

@enduml
