@startuml

    class TablePaneController {
        -spec: HybridSpecification
        -definedVars: ObservableSet<String>
        -durationColumn: DurationsColumnController
        -table: TablePane
        -selection: Selection
        -inputTableController: InputTableController
        +TablePaneController(spec:HybridSpecification, definedVars:ObservableSet<String>, types:ObservableList<Type>, ioVars:ObservableList<IOVariable>)
        +addIOVariable(ioVar:IOVariable): void
        +getView(): TablePane
    }

@enduml
