@startuml

    class TableColumnController {
        -width: IntegerProperty
        -types: ObservableList<Type>
        -typeNames: ObservableList<String>
        -cells: ObservableList<HybridCellController>
        -ioVar: ObjectProperty<VariableIdentifier>
        -problems: ObservableList<SpecProblem>
        -tableColumn: TableColumn
        +TableColumnController(types:ObservableList<Type>, ioVars:ObservableList<IOVariable>, ioVar:ObjectProperty<VariableIdentifier>, config:ColumnConfig)
        +onProblemsChange(problems:List<SpecProblem>): void
        +getWidthProperty(): IntegerProperty
        +getWidth(): int
        +getCells(): ObservableList<HybridCellController>
        +getView(): TableColumn
    }

@enduml
