@startuml

    abstract class RowActionColumnController {
        +RowActionColumnController(durations:DurationsColumnController)
        {abstract} +removeButton(row:int): void
        {abstract} +addButton(row:int, cell:HybridCellController): void
        {abstract} +getView(): Node
    }

@enduml
