@startuml

    class RowEvent {
        {static} +ADD_ROW_BELOW: EventType<RowEvent>
        {static} +REMOVE_ROW: EventType<RowEvent>
        {static} +COMMENT_ROW: EventType<RowEvent>
        -rowNumber: int
        +RowEvent(source:Node, type:EventType<RowEvent>, rowNumber:int)
    }

@enduml
