@startuml

    class FreeVariableSet {
        -variableSet: List<FreeVariable>
        -listeners: List<Consumer<FreeVariableSet>>
        +FreeVariableSet(variableSet:List<FreeVariable>)
        +addChangeListener(listener:Consumer<FreeVariableSet>): void
        +getVariableSet(): List<FreeVariable>
        +setVariableSet(variableSet:List<FreeVariable>): void
    }

@enduml
