@startuml

    class IOVariable {
        -category: VariableCategory
        -type: Type
        +IOVariable(category:VariableCategory, type:Type)
        +getCategory(): VariableCategory
        +getType(): Type
        +setType(type:Type): void
    }

@enduml
