@startuml

    class Selection {
        -listener: List<Consumer<Selection>>
        -variableIdentifier: Optional<VariableIdentifier>
        -row: Optional<Integer>
        +Selection(variableIdentifier:VariableIdentifier, row:int)
        +Selection()
        +getVariableIdentifier(): Optional<VariableIdentifier>
        +getRow(): Optional<Integer>
        +setVariableIdentifier(variableIdentifier:VariableIdentifier): void
        +setRow(row:int): void
        +addListener(listener:Consumer<Selection>): void
    }

@enduml
