@startuml

    class TypeInt {
        +match(matchIntType:Supplier<R>, matchBoolType:Supplier<R>, matchEnumType:Function<TypeEnum, R>): R
        +checksAgainst(other:Type): boolean
        +getTypeName(): String
    }

@enduml
