@startuml

    class ValueEnum {
        -enumValue: String
        -enumType: TypeEnum
        +ValueEnum(enumValue:String, enumType:TypeEnum)
        +match(matchInt:IntFunction<R>, matchBoolean:Function<Boolean, R>, matchEnum:Function<ValueEnum, R>): R
        +getType(): Type
        +getEnumValue(): String
    }

@enduml
