@startuml

    class ValueInt {
        -value: int
        +ValueInt(value:int)
        +match(matchInt:IntFunction<R>, matchBoolean:Function<Boolean, R>, matchEnum:Function<ValueEnum, R>): R
        +getType(): Type
    }

@enduml
