@startuml

    abstract class CategoryTimingDiagramCollection {
        -view: CategoryTimingDiagramCollectionView
        -spec: HybridSpecification
        +CategoryTimingDiagramCollection(spec:HybridSpecification)
        +getView(): CategoryTimingDiagramCollectionView
    }

@enduml
