@startuml

    class InputVariablesTimingDiagramCollection {
        +InputVariablesTimingDiagramCollection(concreteSpecification:ConcreteSpecification, ioVariables:ObservableList<IOVariable>, selection:Selection)
    }

@enduml
