@startuml

    class OutputVariablesTimingDiagramCollection {
        +OutputVariablesTimingDiagramCollection(concreteSpecification:ConcreteSpecification, ioVariables:ObservableList<IOVariable>, selection:Selection)
    }

@enduml
