@startuml

    class TimingDiagramCollectionController {
        -spec: HybridSpecification
        +TimingDiagramCollectionController(spec:HybridSpecification)
        +getView(): TimingDiagramCollectionView
    }

@enduml
