@startuml

    namespace edu.kit.iti.formal.stvs.logic.verification {

        class VerificationThread {
            -code: Code
            -specification: ConstraintSpecification
            +VerificationThread(code:Code, specification:ConstraintSpecification)
            +run(): void
        }

        class VerificationEngine {
            -exporter: VerificationExporter
            -importer: VerificationImporter
            -result: VerificationResult
            -verificationFinishedListener: Consumer<VerificationResult>
            +VerificationEngine(verificationFinishedListener:Consumer<VerificationResult>)
            +startVerification(code:Code, spec:ConstraintSpecification): void
        }

        class java.lang.Thread
        java.lang.Thread <|-- VerificationThread

    }

@enduml
