/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Philipp' at '08.11.16 15:54' with Gradle 3.1
 *
 * @author Philipp, @date 08.11.16 15:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
