@startuml

    namespace edu.kit.iti.formal.stvs.model.verification {

        class VerificationResult {
            +isSuccessful(): boolean
            +getCounterExample(): ConcreteSpecification
        }

    }

@enduml
