@startuml

    namespace edu.kit.iti.formal.stvs.logic.io {

        class ImportException {
        }

        class VerificationImporter {
            +doImport(verificationResultXML:String): VerificationResult
        }

        class XMLExporter {
            +exportSession(code:Code, specs:Collection<SpecificationTable>, config:GlobalConfig, history:History): Node
            +exportVerificationScenario(testCase:VerificationScenario): Node
            +exportTable(table:SpecificationTable): Node
            +exportConfig(config:GlobalConfig): Node
            +exportHistory(history:History): Node
            +writeToFile(xml:Node, filename:String): void
        }

        class VerificationExporter {
            +export(): Node
        }

        class XMLImporter {
            +readFromFile(fileName:String): Node
            +importVerificationScenario(node:Node): VerificationScenario
            +importTable(node:Node): SpecificationTable
            +importConfig(node:Node): GlobalConfig
            +importHistory(node:Node): History
        }

        class java.lang.Exception
        java.lang.Exception <|-- ImportException

    }

@enduml
