@startuml

    class XMLImporter {
        +readFromFile(fileName:String): Node
        +importVerificationScenario(node:Node): VerificationScenario
        +importTable(node:Node): SpecificationTable
        +importConfig(node:Node): GlobalConfig
        +importHistory(node:Node): History
    }

@enduml
