@startuml

    namespace edu.kit.iti.formal.stvs.logic.specification {

        class RowSolver {
            -cycleSolvers: Stack<CycleSolver>
            +RowSolver(duration:int, rownum:int)
            +solve(): boolean
        }

        class CycleSolver {
            +solve(): boolean
            +getModel(): Model
        }

        class ConcretizerContext {
            -ioVars: HashMap<IOVariable, Value>
            -constraintVars: HashMap<String, Value>
            +getIoVars(): HashMap<IOVariable, Value>
            +getConstraintVars(): HashMap<String, Value>
        }

        class SpecificationConcretizer {
            -concreteSpecification: ConcreteSpecification
            -constraintSpecification: ConstraintSpecification
            -rowSolverStack: Stack<RowSolver>
            +SpecificationConcretizer(context:ConcretizerContext)
            +addSuccessfulConcretizationListener(listener:Consumer<ConcreteSpecification>): void
            +onIOVariablesChange(changedIOVariables:ArrayList<IOVariable>): void
            +getConcreteSpecification(): ConcreteSpecification
            +onSpecificationChanged(spec:ConstraintSpecification): void
        }

        SpecificationConcretizer --> ConcretizerContext: context

    }

@enduml
