// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

/************************************************************/
/**
 * 
 */
public enum BinaryOperator {
	/**
	 * 
	 */
	PLUS,
	/**
	 * 
	 */
	MINUS,
	/**
	 * 
	 */
	DIV,
	/**
	 * 
	 */
	MUL,
	/**
	 * 
	 */
	AND,
	/**
	 * 
	 */
	OR,
	/**
	 * 
	 */
	LESS_THAN,
	/**
	 * 
	 */
	LESS_EQUAL,
	/**
	 * 
	 */
	GREATER_THAN,
	/**
	 * 
	 */
	GREATER_EQUAL,
	/**
	 * 
	 */
	XOR,
	/**
	 * 
	 */
	EQUAL,
	/**
	 * 
	 */
	NOT_EQUAL;
};
