// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

import edu.kit.iti.formal.smv.ast.Top;

/************************************************************/
/**
 * 
 */
public abstract class Expression extends Top {

	/**
	 * 
	 */
	public abstract DataType getDataType();
};
