// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

import edu.kit.iti.formal.smv.ast.Expression;

/************************************************************/
/**
 * 
 */
public class Literal extends Expression {
	/**
	 * 
	 */
	public DataType dataType;
	
	/**
	 * 
	 */
	public Object value;

	@Override
	public DataType getDataType() {
		return dataType;
	}
};
