// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

import java.util.ArrayList;
import java.util.List;

import edu.kit.iti.formal.smv.Visitor;
import edu.kit.iti.formal.smv.ast.Top;
import edu.kit.iti.formal.smv.ast.Variable;

/************************************************************/
/**
 * 
 */
public class Module extends Top {
	/**
	 * 
	 */
	public List<Variable> inputvars = new ArrayList<>();
	/**
	 * 
	 */
	public List<Variable> statevars = new ArrayList<>();
	/**
	 * 
	 */
	public List<Variable> frozenvars = new ArrayList<>();
	
	
	public List<Assignment> init = new ArrayList<>();
	
	
	public List<Assignment> next = new ArrayList<>();
	public String name;
	
	public <T> T visit(Visitor<T> visitor) {
		return visitor.visit(this);
	}
};
