// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

import edu.kit.iti.formal.smv.SMVAstVisitor;

/************************************************************/
/**
 * 
 */
public class SAssignment extends SMVAst {
	/**
	 * 
	 */
	public SVariable target;
	/**
	 * 
	 */
	public SMVExpr expr;

	public SAssignment(SVariable v, SMVExpr object) {
		target = v;
		expr = object;
	}

	public <T> T accept(SMVAstVisitor<T> visitor) {
		return visitor.visit(this);
	}

};
