// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

/************************************************************/

/**
 *
 */
public enum SBinaryOperator {
    /**
     *
     */
    PLUS("+"),
    /**
     *
     */
    MINUS("-"),
    /**
     *
     */
    DIV("/"),
    /**
     *
     */
    MUL("*"),
    /**
     *
     */
    AND("&"),
    /**
     *
     */
    OR("|"),
    /**
     *
     */
    LESS_THAN("<"),
    /**
     *
     */
    LESS_EQUAL("<="),
    /**
     *
     */
    GREATER_THAN(">"),
    /**
     *
     */
    GREATER_EQUAL(">="),
    /**
     *
     */
    XOR("^"),
    /**
     *
     */
    EQUAL("="),
    /**
     *
     */
    NOT_EQUAL("!=");

    private final String symbol;

    SBinaryOperator(String symbol) {
        this.symbol = symbol;
    }

    public String symbol() {
        return symbol;
    }
}
