// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

import edu.kit.iti.formal.smv.SMVAstVisitor;

/************************************************************/

/**
 *
 */
public class SLiteral extends SMVExpr {
    public static final SMVExpr TRUE = new SLiteral(SMVType.BOOLEAN, true);

    public static final SMVExpr FALSE = new SLiteral(SMVType.BOOLEAN, false);

    /**
     *
     */
    public SMVType dataType;

    /**
     *
     */
    public Object value;

    public SLiteral() {
    }

    public SLiteral(SMVType dt, Object value) {
        this.value = value;
        dataType = dt;
    }

    public SMVType getSMVType() {
        return dataType;
    }

    @Override
    public String toString() {
        return dataType.format(value);
    }

    @Override
    public <T> T accept(SMVAstVisitor<T> visitor) {
        return visitor.visit(this);
    }
}
