// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

import edu.kit.iti.formal.smv.SMVAstVisitor;

/************************************************************/
/**
 * 
 */
abstract public class SMVAst {
	public abstract <T> T accept(SMVAstVisitor<T> visitor);
}
