// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

/************************************************************/
/**
 * 
 */
public abstract class SMVExpr extends SMVAst {

	/**
	 * 
	 */
	public abstract SMVType getSMVType();
};
