// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

/************************************************************/

import edu.kit.iti.formal.smv.SMVAstVisitor;

/**
 *
 */
public class SUnaryExpression extends SMVExpr {
    /**
     *
     */
    public SUnaryOperator operator;
    /**
     *
     */
    public SMVExpr expr;

    public SUnaryExpression(SUnaryOperator op, SMVExpr left) {
        operator=op;
        expr = left;
    }

    public SMVType getSMVType() {
        return expr.getSMVType();
    }

    @Override
    public <T> T accept(SMVAstVisitor<T> visitor) {
        return visitor.visit(this);
    }
}
