// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

import edu.kit.iti.formal.smv.SMVAstVisitor;

/************************************************************/
/**
 * 
 */
public class SVariable extends SMVExpr {

	public String name;
	public SMVType datatype;

	public SVariable() {

	}

	public SVariable(String n, SMVType enumType) {
		name = n;
		datatype = enumType;
	}

    public static SVariable bool(String name) {
		return new SVariable(name, SMVType.BOOLEAN);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof SVariable)) {
			return false;
		}
		SVariable other = (SVariable) obj;
		if (name == null) {
			if (other.name != null) {
				return false;
			}
		} else if (!name.equals(other.name)) {
			return false;
		}
		return true;
	}

	public SMVType getSMVType() {
		return datatype;
	}

	@Override
	public <T> T accept(SMVAstVisitor<T> visitor) {
		return visitor.visit(this);
	}
}
