// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

import edu.kit.iti.formal.smv.Visitor;

/************************************************************/
/**
 * 
 */
public class Top {
	public <T> T visit(Visitor<T> visitor) {
		return visitor.visit(this);
	}
};
