// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

/************************************************************/
/**
 * 
 */
public enum UnaryOperator {
	/**
	 * 
	 */
	NEGATE,
	/**
	 * 
	 */
	MINUS;

	@Override
	public String toString() {
		switch (this) {
		case NEGATE: return "!";
		case MINUS:  return  "-"	;
		}
		return "";
	}
};
