// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

import edu.kit.iti.formal.smv.ast.Expression;
import edu.kit.iti.formal.smv.ast.UnaryOperator;

/************************************************************/
/**
 * 
 */
public class UnaryExpression extends Expression {
	/**
	 * 
	 */
	public UnaryOperator operator;
	/**
	 * 
	 */
	public Expression expression;

	@Override
	public DataType getDataType() {
		return expression.getDataType();
	}
}
