// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

import edu.kit.iti.formal.smv.ast.Expression;
import edu.kit.iti.formal.smv.ast.Top;

/************************************************************/
/**
 * 
 */
public class Variable extends Top {
};
