// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

/*-
 * #%L
 * smv-model
 * %%
 * Copyright (C) 2016 Alexander Weigl
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

import edu.kit.iti.formal.smv.SMVAstVisitor;
import org.jetbrains.annotations.NotNull;

import java.util.LinkedList;
import java.util.List;
import java.util.stream.Collectors;

/************************************************************/

/**
 *
 */
public class SCaseExpression extends SMVExpr {
    public final List<Case> cases = new LinkedList<>();

    public void add(@NotNull SMVExpr condition, @NotNull SMVExpr value) {
        cases.add(new Case(condition, value));
    }

    public SMVExpr compress() {
        // if all cases have the same value then finish
        if (cases.size() == 0) return this;
        int i = 0;
        while (cases.get(i).condition.equals(SLiteral.FALSE))
            i++;
        final Case firstCase = cases.get(i);
        boolean b = firstCase.condition.equals(SLiteral.TRUE)
                || cases.parallelStream().allMatch(aCase -> firstCase.then.equals(aCase.then));
        if (b)
            return firstCase.then;
        //
        SCaseExpression esac = new SCaseExpression();
        Case previous = firstCase;
        SMVExpr condition = compressCondition(previous.condition);

        i++;
        for (; i < cases.size(); i++) {
            Case current = cases.get(i);
            if (current.condition.equals(SLiteral.FALSE))
                continue;
            if (current.condition.equals(SLiteral.TRUE)) {
                esac.addCase(condition, previous.then);
                previous = current;
                condition = current.condition;
                break;
            }
            if (previous.then.equals(current.then)) {
                condition = condition.or(compressCondition(current.condition));
            } else {
                esac.addCase(condition, previous.then);
                previous = current;
                condition = compressCondition(current.condition);
            }
        }
        if (esac.cases.size() == 0)
            return previous.then;
        esac.addCase(condition, previous.then);
        return esac;
    }

    private SMVExpr compressCondition(SMVExpr condition) {
        if (condition instanceof SBinaryExpression) {
            SBinaryExpression binaryExpression = (SBinaryExpression) condition;
            if (binaryExpression.operator.equals(SBinaryOperator.EQUAL)) {
                if (binaryExpression.left.equals(binaryExpression.right))
                    return SLiteral.TRUE;
                if (binaryExpression.left instanceof SLiteral
                        && binaryExpression.right instanceof SLiteral
                        && binaryExpression.left.getSMVType() instanceof SMVType.EnumType
                        && binaryExpression.left.getSMVType().equals(binaryExpression.right.getSMVType()))
                    return binaryExpression.left.equals(binaryExpression.right)
                            ? SLiteral.TRUE : SLiteral.FALSE;
            }
        }
        return condition;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SCaseExpression that = (SCaseExpression) o;

        return cases.equals(that.cases);

    }

    @Override
    public int hashCode() {
        return cases.hashCode();
    }

    public <T> T accept(SMVAstVisitor<T> visitor) {
        return visitor.visit(this);
    }

    public SMVType getSMVType() {
        List<SMVType> list = cases.stream().map((Case a) -> a.then.getSMVType()).collect(Collectors.toList());

        return SMVType.infer(list);
    }

    @Override
    public @NotNull SCaseExpression inModule(@NotNull String module) {
        SCaseExpression sCaseExpression = new SCaseExpression();
        for (Case c : cases) {
            sCaseExpression.add(c.condition.inModule(module), c.then.inModule(module));
        }
        return sCaseExpression;
    }

    public Case addCase(@NotNull SMVExpr cond, @NotNull SMVExpr var) {
        Case c = new Case(cond, var);
        cases.add(c);
        return c;
    }

    /**
     *
     */
    public static class Case {
        /**
         *
         */
        @NotNull
        public final SMVExpr condition;
        /**
         *
         */
        @NotNull
        public final SMVExpr then;

        Case(@NotNull SMVExpr cond, @NotNull SMVExpr var) {
            condition = cond;
            then = var;
        }

        @Override
        public String toString() {
            return ":: " + condition + "->" + then;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            Case aCase = (Case) o;

            return condition.equals(aCase.condition) && then.equals(aCase.then);

        }

        @Override
        public int hashCode() {
            int result = condition.hashCode();
            result = 31 * result + then.hashCode();
            return result;
        }
    }

    @Override
    public String toString() {
        return "if " +
                cases.stream()
                        .map(Case::toString).reduce((a, b) -> a + "\n" + b)
                        .orElse("")
                + " fi";
    }


}
