// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.iti.formal.smv.ast;

/*-
 * #%L
 * smv-model
 * %%
 * Copyright (C) 2016 Alexander Weigl
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

/************************************************************/

/**
 *
 */
public enum SUnaryOperator implements SOperator {
    /**
     *
     */
    NEGATE("!", 1),
    /**
     *
     */
    MINUS("-", 3);

    private final int precedence;
    private String symbol;

    SUnaryOperator(String symbol, int p) {
        this.symbol = symbol;
        precedence = p;
    }

    @Override
    public int precedence() {
        return precedence;
    }

    @Override
    public String symbol() {
        return symbol;
    }

    @Override
    public String toString() {
        return symbol();
    }
}
