@startuml

    class VariableCollectionController {
        -freeVariableSet: FreeVariableSet
        -view: VariableCollection
        +VariableCollectionController(freeVariableSet:FreeVariableSet)
        +getView(): VariableCollection
    }

@enduml
