@startuml

    class VariableController {
        -freeVariable: FreeVariable
        -view: VariableView
        +VariableController(freeVariable:FreeVariable)
        +getView(): Node
    }

@enduml
