@startuml

    namespace edu.kit.iti.formal.stvs.model.io {

        class VerificationScenario {
            -spec: ConstraintSpecification
            -verificationResult: VerificationResult
            -code: Code
        }

    }

@enduml
