package edu.kit.iti.formal.asdl

import java.io.File
import java.io.PrintWriter

class KotlinGenerator(val outputDirectory: String, val topClass: String = "Top", val visitorBaseName: String = "Visitor")
    : Generator() {
    lateinit var file: File
    lateinit var writer: PrintWriter

    override fun visit(m: Module) {
        file = File(outputDirectory, m.pkgName.replace('.', '/'))
                .resolveSibling(m.name + ".kt")
        writer = PrintWriter(file.bufferedWriter())
        writer.printf("""package ${m.pkgName}
             /* This file is auto-generated by an ASDL.
                 Please do not modify. */
        """.trimMargin(), m.pkgName)
        traverse(m)
        writer.close()
    }

    override fun visit(g: Group) {
        writer.print("""
            class ${g.name} ${if(g.parent!=null) ": ${g.parent}" else "" } {

            }
            """.trimIndent())
    }


    override fun visit(g: Leaf) {
        writer.print("""
            class ${g.name} ${if(g.parent!=null) ": ${g.parent}" else "" } {

            }
            """.trimIndent())
    }

}