package edu.kit.iti.formal.automation.visitors;

public enum Sections {
    KEYWORD, STATEMENT, CASE_INTEGER_CONDITION, CASE_ENUM_CONDITION, OPERATOR, BINARY_EXPRESSION,
    ASSIGNMENT, TYPE_DECL_ENUM, TYPE_NAME, REPEAT, WHILE, UNARY_EXPRESSION, TYPE_DECL, CASE_STATEMENT, VARIABLE,
    SUBSCRIPT, STATEMENT_BLOCK, PROGRAM, VALUE, EXPRESSION_LIST, SEPARATOR, FUNC_CALL, FOR, FB, IFSTATEMENT, FB_CALL,
    CASE, TYPE_DECL_SIMPLE, VARIABLES_DEFINITION, COMMENT, TYPE_DECL_DECL, VARIABLES_DEFINITIONS, SPECIAL_VARIABLE, CONSTANT, ERROR
}