@startuml

    class STVSMainScene {
        -rootController: STVSRootController
        +STVSMainScene(root:Parent)
        +getRootController(): STVSRootController
        +setRootController(rootController:STVSRootController): void
    }

@enduml
