@startuml

    class ConstraintSpecification {
        -problemsListeners: List<Consumer<List<SpecProblem>>>
        -typeContext: Set<Type>
        -freeVariableSet: FreeVariableSet
        +ConstraintSpecification(typeContext:Set<Type>, ioVariables:Set<IOVariable>, freeVariableSet:FreeVariableSet)
        +addProblemsListener(listener:Consumer<List<SpecProblem>>): void
        +getProblems(): List<SpecProblem>
        +getTypeContext(): Set<Type>
        +setTypeContext(typeContext:Set<Type>): void
        +getFreeVariableSet(): FreeVariableSet
    }

@enduml
