@startuml

    class ConstraintDuration {
        -bounds: LowerBoundedInterval
        -userInputString: String
        -comment: String
        -Listeners: List<Consumer<LowerBoundedInterval>>
        +ConstraintDuration(bounds:LowerBoundedInterval)
        +getBounds(): LowerBoundedInterval
        +setBounds(bounds:LowerBoundedInterval): void
        +getUserInputString(): String
        +setUserInputString(input:String): void
        +addBoundsListener(listener:Consumer<LowerBoundedInterval>): void
        +addUserInputStringListener(listener:Consumer<String>): void
        +setComment(comment:String): void
        +getComment(): String
        +addCommentListener(consumer:Consumer<Commentable>): void
    }

@enduml
