@startuml

    class SpecificationTable.RowChangeInfo<C, D> {
        +row: SpecificationRow<C, D>
        +rowNum: int
        +changeType: SpecificationTable.Change
        +RowChangeInfo(row:SpecificationRow<C, D>, rowNum:int, changeType:SpecificationTable.Change)
    }

@enduml
