@startuml

    class SpecificationRow<C, D> {
        -duration: D
        -cells: Map<VariableIdentifier, C>
        +SpecificationRow(duration:D, cells:Map<VariableIdentifier, C>)
        +getEntryForVariable(variable:VariableIdentifier): C
        +getDuration(): D
    }

@enduml
