@startuml

    class SpecificationTable<C, D> {
        -columnsListeners: List<Consumer<SpecificationTable.ColumnChangeInfo<C>>>
        -rowsListeners: List<Consumer<SpecificationTable.RowChangeInfo<C, D>>>
        -durations: List<D>
        +getCell(row:int, column:VariableIdentifier): C
        +getColumn(column:VariableIdentifier): SpecificationColumn<C>
        +addColumn(columnId:VariableIdentifier, column:SpecificationColumn<C>): void
        +removeColumn(columnId:VariableIdentifier): void
        +getRow(row:int): SpecificationRow<C, D>
        +addRow(rowNum:int, row:SpecificationRow<C, D>): void
        +removeRow(rowNum:int): void
        +getDuration(rowNum:int): D
        +addColumnsListener(columnsListener:Consumer<SpecificationTable.ColumnChangeInfo<C>>): void
        +addRowsListener(rowsListener:Consumer<SpecificationTable.RowChangeInfo<C, D>>): void
    }

@enduml
