@startuml

    class SpecificationTabController {
        -definedVars: ObservableSet<String>
        -types: ObservableList<Type>
        -ioVars: ObservableList<IOVariable>
        -spec: HybridSpecification
        +SpecificationTabController(hybridSpecification:HybridSpecification, types:ObservableList<Type>, ioVars:ObservableList<IOVariable>)
        +getView(): SpecificationTab
    }

@enduml
