@startuml

    class SpecificationTab {
        -variableView: VariableView
        -table: TablePane
        -diagram: TimingDiagramCollectionView
        -startButton: Button
        +getTable(): TablePane
        +setTable(table:TablePane): void
        +getDiagram(): TimingDiagramCollectionView
        +setDiagram(diagram:TimingDiagramCollectionView): void
        +getStartButton(): Button
    }

@enduml
