@startuml

    class SpecificationsPaneController {
        -hybridSpecifications: ObservableList<HybridSpecification>
        -types: ObservableList<Type>
        -ioVars: ObservableList<IOVariable>
        -view: SpecificationsPane
        +SpecificationsPaneController(types:ObservableList<Type>, ioVars:ObservableList<IOVariable>, hybridSpecifications:ObservableList<HybridSpecification>)
        +getHybridSpecifications(): ObservableList<HybridSpecification>
        +getView(): SpecificationsPane
    }

@enduml
