TYPE
    Magazin_states_t : (Green_Lamp , Init , Interstep , Magazin_Init , Magazin_Init_2 , Slider_Move_Back , Start_Magazin , Step0 , Step1 , convey);
    Crane_states_t : (Crane_Init , Crane_Init_2 , Crane_Lift_Conveyor , Crane_On_Conveyor , Crane_On_Conveyor_Metallic , Crane_Stop , Crane_Turn_Left_Metallic , Crane_Turn_Left_NOT_Metallic , Init , Interstep , Interstep_2 , Interstep_Check_Workpiece , Magazin_Stop , Start_Crane , Step0 , TimeDelay , Turn_Right , release);
END_TYPE

